### ISSUE TITLE
Support for pull_request_target

### ISSUE THREAD

**Issue by PatrickHeneise** [namoscato/action-tinify#200]
This action fails with

`Error: Unsupported event pull_request_target (currently supported events include push, pull_request)`

```
name: Process Images

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Tinify Image Action
        uses: namoscato/action-tinify@v1.2.6
        with:
          api_key: ${{ secrets.TINIFY_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

`pull_request_target` is a new event type that allows access to the repository secrets (`TINIFY_API_KEY`) when the pull request is coming from a fork.

Maybe remove the event check all together and allow events like `workflow_dispatch` as well? GitHub Actions changes frequently.

For more information, see https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by namoscato** [comment]
@PatrickHeneise, good catch – thanks! I'll take care of this over the weekend.

**Comment by namoscato** [comment]
@PatrickHeneise, https://github.com/namoscato/action-tinify/pull/201 adds support for `pull_request_target`, but I'm running into some issues with [`actions/checkout`](https://github.com/actions/checkout#usage) and git context when actually pushing up the commit.

The existing `push` / `pull_request` events relied on checkout via the source branch:

```yaml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.head_ref }}
```

and pushed via:

```
git push origin
```

which won't work for forked repositories.

I'm still determining the best way to support all contexts; let me know if you have any thoughts in the meantime.
